name: Integration Tests

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: stormeye2000
          github_user: stormeye2000
          repo: cspr-java-sdk-evaluation
          ref: main
          wait_interval: 60
          github_token: ${{ secrets.GHT_EXECUTE_ACTIONS }}
          workflow_file_name: evaluation.yaml
