name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: stormeye2000
          github_user: stormeye2000
          repo: cspr-java-sdk-evaluation
          github_token: ${{ secrets.GHT_EXECUTE_ACTIONS }}
          workflow_file_name: evaluation.yaml
