name: Evaluation

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Setting Up Integration Tests
        run: |
          echo "Setting Up Integration Tests"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: stormeye2000
          repo: cspr-java-sdk-evaluation
          github_token: ${{ secrets.GHT_EXECUTE_ACTIONS }}
          workflow_file_name: deploy.yml
          ref: main
      - name: Running Integration Tests
        run: |
          echo "Running Integration Tests"
          sleep 60s