name: Evaluation

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 60s
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: stormeye2000
          repo: cspr-java-sdk-evaluation
          github_token: ${{ secrets.GHT_EXECUTE_ACTIONS }}
          workflow_file_name: deploy.yml
          ref: main
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 60s