name: generate-jekyll-pages-for-docs

on:
  workflow_dispatch:

jobs:
  generate-jekyll-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Generate pages from present docs folders and templates
        run: bash ./generate-pages.sh
        env:
          MASTER_BRANCH_NAME: origin/main
          SOURCE_INDEX_FILE: README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v8.0.1
